### ISSUE TITLE
Typescript 4.2.2 support

### ISSUE THREAD

**Issue by mmso** [MattiasBuelens/web-streams-adapter#17]
With the latest dom definitions in TypeScript, some types have been removed such as `UnderlyingByteSource`, `ReadableStreamBYOBReader`, or `ReadableByteStreamController` https://github.com/microsoft/TypeScript/pull/42067 

This causes a compilation error if library checking is enabled.

**Comment by MattiasBuelens** [comment]
Riiight, I had updated the Stream DOM types a while back in microsoft/TypeScript-DOM-lib-generator#890, and kind of forgot about it. But now that TypeScript 4.2 is out, those new types have landed as well. So I'm breaking my own projects again. 😅

I'll have a look.

**Comment by lgrahl** [comment]
Hoping a polite ping is appropriate and many thanks for this project. :slightly_smiling_face:

**Comment by MattiasBuelens** [comment]
Found some time to finish this up. Published as v0.1.0. 🙂

Note that, although the "alpha" status is now gone, this is still very much a v0.x project. But at least it's somewhat usable already. 😁
